# Generated by Django 4.2.4 on 2023-09-04 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=35)),
                ('proteine', models.IntegerField(default=0)),
                ('carboidrati', models.IntegerField(default=0)),
                ('grassi', models.IntegerField(default=0)),
                ('kcal', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipologia', models.CharField(max_length=30)),
                ('proteine', models.IntegerField(default=0)),
                ('carboidrati', models.IntegerField(default=0)),
                ('grassi', models.IntegerField(default=0)),
                ('kcal', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DettaglioDieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.IntegerField(default=0)),
                ('cibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diet.alimento')),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diet.dieta')),
            ],
        ),
    ]
