# Generated by Django 4.2.5 on 2023-10-02 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=35, unique=True)),
                ('proteine', models.FloatField(default=0)),
                ('carboidrati', models.FloatField(default=0)),
                ('grassi', models.FloatField(default=0)),
                ('cal', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Alimenti',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipologia', models.CharField(max_length=30)),
                ('descrizione', models.CharField(blank=True, max_length=300)),
                ('data_inizio', models.DateField(blank=True, null=True)),
                ('data_fine', models.DateField(blank=True, null=True)),
                ('my_user', models.ForeignKey(db_column='my_user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GiornoDieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giorno', models.IntegerField(default=1)),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diet.dieta')),
            ],
        ),
        migrations.CreateModel(
            name='DettaglioDieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasto', models.CharField(choices=[('1', 'Colazione'), ('2', 'Spuntino'), ('3', 'Pranzo'), ('4', 'Merenda'), ('5', 'Cena')], default='Sgarro', max_length=10)),
                ('quantita', models.IntegerField(default=0)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diet.alimento')),
                ('giorno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Diet.giornodieta')),
            ],
            options={
                'ordering': ['pasto'],
            },
        ),
    ]
