# Generated by Django 4.2.4 on 2023-09-05 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Diet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alimento',
            old_name='kcal',
            new_name='cal',
        ),
        migrations.RenameField(
            model_name='dieta',
            old_name='kcal',
            new_name='cal',
        ),
    ]
