# Generated by Django 4.2.5 on 2023-10-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giornodieta',
            name='cal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='giornodieta',
            name='carboidrati',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='giornodieta',
            name='grassi',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='giornodieta',
            name='proteine',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='giornodieta',
            name='giorno',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
