# Generated by Django 4.2.4 on 2023-09-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diet', '0002_rename_kcal_alimento_cal_rename_kcal_dieta_cal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dettagliodieta',
            old_name='cibo',
            new_name='alimento',
        ),
        migrations.RemoveField(
            model_name='dieta',
            name='cal',
        ),
        migrations.RemoveField(
            model_name='dieta',
            name='carboidrati',
        ),
        migrations.RemoveField(
            model_name='dieta',
            name='grassi',
        ),
        migrations.RemoveField(
            model_name='dieta',
            name='proteine',
        ),
        migrations.AddField(
            model_name='dettagliodieta',
            name='giorni',
            field=models.CharField(choices=[('lunedi', 'Lunedi'), ('martedi', 'Martedi'), ('mercoledi', 'Mercoledi'), ('giovedi', 'Giovedi'), ('venerdi', 'Venerdi'), ('sgarro', 'Sgarro')], default='Colazione', max_length=10),
        ),
        migrations.AddField(
            model_name='dettagliodieta',
            name='pasto',
            field=models.CharField(choices=[('colazione', 'Colazione'), ('spuntino', 'Spuntino'), ('pranzo', 'Pranzo'), ('merenda', 'Merenda'), ('cena', 'Cena')], default='Sgarro', max_length=10),
        ),
        migrations.AddField(
            model_name='dieta',
            name='descrizione',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
