# Generated by Django 4.2.4 on 2023-10-05 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Diet', '0003_alter_giornodieta_giorno'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DettaglioDieta',
            new_name='DettaglioGiornoAlimento',
        ),
    ]
