# Generated by Django 4.2.4 on 2023-10-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diet', '0004_rename_dettagliodieta_dettagliogiornoalimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giornodieta',
            name='giorno',
            field=models.IntegerField(auto_created=True, unique=True),
        ),
    ]
