# Generated by Django 4.2.4 on 2023-10-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diet', '0005_alter_giornodieta_giorno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dettagliogiornoalimento',
            name='pasto',
            field=models.CharField(choices=[('1 Colazione', '1 Colazione'), ('2 Spuntino', '2 Spuntino'), ('3 Pranzo', '3 Pranzo'), ('4 Merenda', '4 Merenda'), ('5 Cena', '5 Cena')], default='Sgarro', max_length=15),
        ),
    ]
