# Generated by Django 4.2.4 on 2023-09-04 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Esercizio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('descrizione', models.CharField(blank=True, max_length=450)),
                ('immagine', models.ImageField(blank=True, upload_to='immagini_es')),
            ],
            options={
                'verbose_name_plural': 'Esercizi',
            },
        ),
        migrations.CreateModel(
            name='Scheda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipologia', models.CharField(max_length=20)),
                ('descrizione', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Schede',
            },
        ),
        migrations.CreateModel(
            name='DettaglioEsercizioScheda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giorno', models.IntegerField(default=0)),
                ('serie', models.IntegerField(default=0)),
                ('ripetizioni', models.IntegerField(default=0)),
                ('recupero', models.IntegerField(default=0)),
                ('descrizione', models.CharField(blank=True, max_length=350)),
                ('esercizio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workout.esercizio')),
                ('scheda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workout.scheda')),
            ],
        ),
    ]
