# Generated by Django 4.2.4 on 2023-10-12 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Esercizio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('descrizione', models.CharField(blank=True, max_length=450)),
                ('distretto_target', models.CharField(choices=[('spalle', 'Spale'), ('pettorali', 'Pettorali'), ('dorsali', 'Dorsali'), ('gambe', 'Gambe'), ('braccia', 'Braccia'), ('all', 'All')], default='All', max_length=20)),
                ('immagine', models.ImageField(blank=True, upload_to='immagini_es')),
            ],
            options={
                'verbose_name_plural': 'Esercizi',
            },
        ),
        migrations.CreateModel(
            name='Scheda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipologia', models.CharField(max_length=20)),
                ('descrizione', models.CharField(max_length=250)),
                ('data_inizio', models.DateField(blank=True, null=True)),
                ('data_fine', models.DateField(blank=True, null=True)),
                ('my_user', models.ForeignKey(db_column='my_user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Schede',
            },
        ),
        migrations.CreateModel(
            name='GiornoScheda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giorno', models.IntegerField(default=1)),
                ('descrizione_giorno', models.CharField(blank=True, max_length=300)),
                ('Scheda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workout.scheda')),
            ],
        ),
        migrations.CreateModel(
            name='DettaglioEsercizioGiorno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.IntegerField(default=0)),
                ('ripetizioni', models.IntegerField(default=0)),
                ('recupero', models.IntegerField(default=0)),
                ('descrizione', models.CharField(blank=True, max_length=350)),
                ('esercizio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workout.esercizio')),
                ('giorno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workout.giornoscheda')),
            ],
        ),
    ]
