# Generated by Django 4.2.4 on 2023-10-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esercizio',
            name='immagine',
            field=models.ImageField(blank=True, upload_to='immagini_es/'),
        ),
    ]
