# Generated by Django 4.2.5 on 2023-10-03 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Workout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dettaglioesercizioscheda',
            name='scheda',
        ),
        migrations.CreateModel(
            name='GiornoScheda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giorno', models.IntegerField(default=1)),
                ('descrizione_giorno', models.CharField(blank=True, max_length=300)),
                ('Scheda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workout.scheda')),
            ],
        ),
        migrations.AlterField(
            model_name='dettaglioesercizioscheda',
            name='giorno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workout.giornoscheda'),
        ),
    ]
