# Generated by Django 4.2.4 on 2023-10-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workout', '0002_alter_esercizio_immagine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giornoscheda',
            name='descrizione_giorno',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
